version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: 'foodgram_db'
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: nikpetrishchev/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: nikpetrishchev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  nginx:
    image: nikpetrishchev/foodgram_nginx
    env_file: .env
    ports:
      - '8000:80'
    volumes:
#      - static:/staticfiles/
#      - media:/media/
#      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
