version: '3.3'

networks:
  django-network:
    driver: bridge
volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: nikpetrishchev/foodgram_backend
    env_file: .env
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - static:/backend_static/app/static/
      - media:/app/media/

  frontend:
    image: nikpetrishchev/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - '8000:80'
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
