version: '3.3'

networks:
  django-network:
    driver: bridge
volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: nikpetrishchev/foodgram_backend
    env_file: .env
    restart: always
    volumes:
      - static:/backend_static/app/static/
      - media:/media/

  frontend:
    image: nikpetrishchev/foodgram_frontend
#    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ./frontend/:/app/result_build/
#      - static:/frontend_static/api/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - '8000:80'
    volumes:
#      - static:/staticfiles/
#      - media:/media/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#      - ./nginx_conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
