# Generated by Django 3.2.3 on 2024-02-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='measure',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
