# Generated by Django 3.2.3 on 2024-03-05 17:47

# Django Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='no_same_tags'),
        ),
    ]
