# Generated by Django 3.2.3 on 2024-03-05 17:49

# Django Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipetag_no_same_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='no_same_ingredients'),
        ),
    ]
