# Generated by Django 3.2.3 on 2024-02-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240217_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_to_do',
            new_name='cooking_time',
        ),
    ]
